language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g hexo

script:
  - hexo generate --deploy

# after_script:
#   - cd dist
#   - git init
#   - git config user.name "iissnan"
#   - git config user.email "iissnan@gmail.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master
# # E: Build LifeCycle

# branches:
#   only:
#     - master
# env:
#  global:
#    - GH_REF: github.com/iissnan/theme-next-docs.git
#    - secure: ""
