language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- hexo clean
script:
- hexo generate
after_script:
- rm -rf .deploy_git
- mkdir .deploy_git
- cp -R public/* .deploy_git/
- cd .deploy_git
- git init
- git config user.name "daorren"
- git config user.email "daorenmc@gmail.com"
- git add .
- git commit -m "Update by Travis CI"
- git push --force  "https://${GH_TOKEN}@${GH_REF}" master
branches:
  only:
  - code
env:
  global:
  - GH_REF: github.com/daorren/daorren.github.io.git
  - secure: guBAfnCKxtNBi72JPFSYWRD7g1PiLOKgT+QcHCS1pWg/EFQWcMlZzlScnHvTHotZS3qiCIZ5VFVEh0wz/P5P7Dr6aD4UXoQEA1w/vN01rDekkRx53dLLbY1v+6/Kdsynu5f6qeOJk6u13r1fZ+FOxCLcG8Zu3ZrZO4DSlCnCWcOjInxvsWy2eaHHnqDryLfKXTmLejKH0NVhWT0agw/reVK6FLsfxYBWI3y9/jLucyV1M1j+XFtfwpiCjgaWpvU8JTt7Z54zvKoWTEffPUG0T1HLOydfrc7FIdwsnIo62VJxq/v3vCiE1xZngr6KdUG34ONq5aqXnr0DZTJc+qoysTJ243eZbDvDa5BwgwmhyPw7elyXtmrLbRASzZ84Jl/MG29p8XSBgk2SB0zwqjYQnTQVse84udKvYOnNmC5T4HzSvxcCQrhUFMPXWf1YLchpsBd92vzYp9Fa4AyouX5lOc3+PQq86qWo1EH8vdbzSAr69QP+26TiZld+TxPDKAyqgG0WLof4xHHAZKV60PAsbcn+UflCMbKDcSXNj3Is5vik8TIZWRrrAAwg+wwIVHKQ6jJvizNpC2demakaR5WRTwTfcQ8EmN6Mv3OJgpqal4K54yyBO4sHc2+nNOsSIIjxASSDSMVyZ1fFo/Vf4Kwk6hZvNWs0lyf7ancOkDqeSP4=
